server:
  port: 8080
spring:
  application:
    name: "SCA_PostsAndComments-ALPHA"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: false
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://mongodb:27017/SCA_PostAndComments"
  rabbitmq:
    host: "rabbitmq"
    username: "guest"
    password: "guest"
    virtual-host: "/"
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "*"