server:
  port: 8081
spring:
  application:
    name: "SCA_PostsAndComments-BETA"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: false
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://mongodb:27017/SCA_PostAndComments"
  rabbitmq:
    host: "rabbitmq"
    username: "guest"
    password: "guest"
    virtual-host: "/"
    port: 5672
cors:
  allowed-origins: "*"